// Code generated by ogen, DO NOT EDIT.

package backlog

type AddCommentReq struct {
	Content        string `json:"content"`
	NotifiedUserId []int  `json:"notifiedUserId"`
}

// GetContent returns the value of Content.
func (s *AddCommentReq) GetContent() string {
	return s.Content
}

// GetNotifiedUserId returns the value of NotifiedUserId.
func (s *AddCommentReq) GetNotifiedUserId() []int {
	return s.NotifiedUserId
}

// SetContent sets the value of Content.
func (s *AddCommentReq) SetContent(val string) {
	s.Content = val
}

// SetNotifiedUserId sets the value of NotifiedUserId.
func (s *AddCommentReq) SetNotifiedUserId(val []int) {
	s.NotifiedUserId = val
}

type ApiKey struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiKey) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *ApiKey) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKey) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *ApiKey) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Attachment
type Attachment struct {
	ID          OptInt    `json:"id"`
	Name        OptString `json:"name"`
	Size        OptInt    `json:"size"`
	CreatedUser OptUser   `json:"createdUser"`
	Created     OptString `json:"created"`
}

// GetID returns the value of ID.
func (s *Attachment) GetID() OptInt {
	return s.ID
}

// GetName returns the value of Name.
func (s *Attachment) GetName() OptString {
	return s.Name
}

// GetSize returns the value of Size.
func (s *Attachment) GetSize() OptInt {
	return s.Size
}

// GetCreatedUser returns the value of CreatedUser.
func (s *Attachment) GetCreatedUser() OptUser {
	return s.CreatedUser
}

// GetCreated returns the value of Created.
func (s *Attachment) GetCreated() OptString {
	return s.Created
}

// SetID sets the value of ID.
func (s *Attachment) SetID(val OptInt) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Attachment) SetName(val OptString) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *Attachment) SetSize(val OptInt) {
	s.Size = val
}

// SetCreatedUser sets the value of CreatedUser.
func (s *Attachment) SetCreatedUser(val OptUser) {
	s.CreatedUser = val
}

// SetCreated sets the value of Created.
func (s *Attachment) SetCreated(val OptString) {
	s.Created = val
}

// Ref: #/components/schemas/Category
type Category struct {
	ID           OptInt    `json:"id"`
	Name         OptString `json:"name"`
	DisplayOrder OptInt    `json:"displayOrder"`
}

// GetID returns the value of ID.
func (s *Category) GetID() OptInt {
	return s.ID
}

// GetName returns the value of Name.
func (s *Category) GetName() OptString {
	return s.Name
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *Category) GetDisplayOrder() OptInt {
	return s.DisplayOrder
}

// SetID sets the value of ID.
func (s *Category) SetID(val OptInt) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Category) SetName(val OptString) {
	s.Name = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *Category) SetDisplayOrder(val OptInt) {
	s.DisplayOrder = val
}

// Ref: #/components/schemas/ChangeLog
type ChangeLog struct {
	Field         OptString    `json:"field"`
	NewValue      OptNilString `json:"newValue"`
	OriginalValue OptNilString `json:"originalValue"`
}

// GetField returns the value of Field.
func (s *ChangeLog) GetField() OptString {
	return s.Field
}

// GetNewValue returns the value of NewValue.
func (s *ChangeLog) GetNewValue() OptNilString {
	return s.NewValue
}

// GetOriginalValue returns the value of OriginalValue.
func (s *ChangeLog) GetOriginalValue() OptNilString {
	return s.OriginalValue
}

// SetField sets the value of Field.
func (s *ChangeLog) SetField(val OptString) {
	s.Field = val
}

// SetNewValue sets the value of NewValue.
func (s *ChangeLog) SetNewValue(val OptNilString) {
	s.NewValue = val
}

// SetOriginalValue sets the value of OriginalValue.
func (s *ChangeLog) SetOriginalValue(val OptNilString) {
	s.OriginalValue = val
}

// Ref: #/components/schemas/Comment
type Comment struct {
	ID            OptInt         `json:"id"`
	Content       OptString      `json:"content"`
	ChangeLog     []ChangeLog    `json:"changeLog"`
	CreatedUser   OptUser        `json:"createdUser"`
	Created       OptString      `json:"created"`
	Updated       OptNilString   `json:"updated"`
	Stars         []Star         `json:"stars"`
	Notifications []Notification `json:"notifications"`
}

// GetID returns the value of ID.
func (s *Comment) GetID() OptInt {
	return s.ID
}

// GetContent returns the value of Content.
func (s *Comment) GetContent() OptString {
	return s.Content
}

// GetChangeLog returns the value of ChangeLog.
func (s *Comment) GetChangeLog() []ChangeLog {
	return s.ChangeLog
}

// GetCreatedUser returns the value of CreatedUser.
func (s *Comment) GetCreatedUser() OptUser {
	return s.CreatedUser
}

// GetCreated returns the value of Created.
func (s *Comment) GetCreated() OptString {
	return s.Created
}

// GetUpdated returns the value of Updated.
func (s *Comment) GetUpdated() OptNilString {
	return s.Updated
}

// GetStars returns the value of Stars.
func (s *Comment) GetStars() []Star {
	return s.Stars
}

// GetNotifications returns the value of Notifications.
func (s *Comment) GetNotifications() []Notification {
	return s.Notifications
}

// SetID sets the value of ID.
func (s *Comment) SetID(val OptInt) {
	s.ID = val
}

// SetContent sets the value of Content.
func (s *Comment) SetContent(val OptString) {
	s.Content = val
}

// SetChangeLog sets the value of ChangeLog.
func (s *Comment) SetChangeLog(val []ChangeLog) {
	s.ChangeLog = val
}

// SetCreatedUser sets the value of CreatedUser.
func (s *Comment) SetCreatedUser(val OptUser) {
	s.CreatedUser = val
}

// SetCreated sets the value of Created.
func (s *Comment) SetCreated(val OptString) {
	s.Created = val
}

// SetUpdated sets the value of Updated.
func (s *Comment) SetUpdated(val OptNilString) {
	s.Updated = val
}

// SetStars sets the value of Stars.
func (s *Comment) SetStars(val []Star) {
	s.Stars = val
}

// SetNotifications sets the value of Notifications.
func (s *Comment) SetNotifications(val []Notification) {
	s.Notifications = val
}

type CreateIssueReq struct {
	ProjectId      int        `json:"projectId"`
	Summary        string     `json:"summary"`
	IssueTypeId    int        `json:"issueTypeId"`
	PriorityId     int        `json:"priorityId"`
	Description    OptString  `json:"description"`
	StartDate      OptString  `json:"startDate"`
	DueDate        OptString  `json:"dueDate"`
	EstimatedHours OptFloat64 `json:"estimatedHours"`
	ActualHours    OptFloat64 `json:"actualHours"`
	CategoryId     []int      `json:"categoryId"`
	VersionId      []int      `json:"versionId"`
	MilestoneId    []int      `json:"milestoneId"`
	AssigneeId     OptInt     `json:"assigneeId"`
	ParentIssueId  OptInt     `json:"parentIssueId"`
}

// GetProjectId returns the value of ProjectId.
func (s *CreateIssueReq) GetProjectId() int {
	return s.ProjectId
}

// GetSummary returns the value of Summary.
func (s *CreateIssueReq) GetSummary() string {
	return s.Summary
}

// GetIssueTypeId returns the value of IssueTypeId.
func (s *CreateIssueReq) GetIssueTypeId() int {
	return s.IssueTypeId
}

// GetPriorityId returns the value of PriorityId.
func (s *CreateIssueReq) GetPriorityId() int {
	return s.PriorityId
}

// GetDescription returns the value of Description.
func (s *CreateIssueReq) GetDescription() OptString {
	return s.Description
}

// GetStartDate returns the value of StartDate.
func (s *CreateIssueReq) GetStartDate() OptString {
	return s.StartDate
}

// GetDueDate returns the value of DueDate.
func (s *CreateIssueReq) GetDueDate() OptString {
	return s.DueDate
}

// GetEstimatedHours returns the value of EstimatedHours.
func (s *CreateIssueReq) GetEstimatedHours() OptFloat64 {
	return s.EstimatedHours
}

// GetActualHours returns the value of ActualHours.
func (s *CreateIssueReq) GetActualHours() OptFloat64 {
	return s.ActualHours
}

// GetCategoryId returns the value of CategoryId.
func (s *CreateIssueReq) GetCategoryId() []int {
	return s.CategoryId
}

// GetVersionId returns the value of VersionId.
func (s *CreateIssueReq) GetVersionId() []int {
	return s.VersionId
}

// GetMilestoneId returns the value of MilestoneId.
func (s *CreateIssueReq) GetMilestoneId() []int {
	return s.MilestoneId
}

// GetAssigneeId returns the value of AssigneeId.
func (s *CreateIssueReq) GetAssigneeId() OptInt {
	return s.AssigneeId
}

// GetParentIssueId returns the value of ParentIssueId.
func (s *CreateIssueReq) GetParentIssueId() OptInt {
	return s.ParentIssueId
}

// SetProjectId sets the value of ProjectId.
func (s *CreateIssueReq) SetProjectId(val int) {
	s.ProjectId = val
}

// SetSummary sets the value of Summary.
func (s *CreateIssueReq) SetSummary(val string) {
	s.Summary = val
}

// SetIssueTypeId sets the value of IssueTypeId.
func (s *CreateIssueReq) SetIssueTypeId(val int) {
	s.IssueTypeId = val
}

// SetPriorityId sets the value of PriorityId.
func (s *CreateIssueReq) SetPriorityId(val int) {
	s.PriorityId = val
}

// SetDescription sets the value of Description.
func (s *CreateIssueReq) SetDescription(val OptString) {
	s.Description = val
}

// SetStartDate sets the value of StartDate.
func (s *CreateIssueReq) SetStartDate(val OptString) {
	s.StartDate = val
}

// SetDueDate sets the value of DueDate.
func (s *CreateIssueReq) SetDueDate(val OptString) {
	s.DueDate = val
}

// SetEstimatedHours sets the value of EstimatedHours.
func (s *CreateIssueReq) SetEstimatedHours(val OptFloat64) {
	s.EstimatedHours = val
}

// SetActualHours sets the value of ActualHours.
func (s *CreateIssueReq) SetActualHours(val OptFloat64) {
	s.ActualHours = val
}

// SetCategoryId sets the value of CategoryId.
func (s *CreateIssueReq) SetCategoryId(val []int) {
	s.CategoryId = val
}

// SetVersionId sets the value of VersionId.
func (s *CreateIssueReq) SetVersionId(val []int) {
	s.VersionId = val
}

// SetMilestoneId sets the value of MilestoneId.
func (s *CreateIssueReq) SetMilestoneId(val []int) {
	s.MilestoneId = val
}

// SetAssigneeId sets the value of AssigneeId.
func (s *CreateIssueReq) SetAssigneeId(val OptInt) {
	s.AssigneeId = val
}

// SetParentIssueId sets the value of ParentIssueId.
func (s *CreateIssueReq) SetParentIssueId(val OptInt) {
	s.ParentIssueId = val
}

type CreateWikiReq struct {
	ProjectId  int       `json:"projectId"`
	Name       string    `json:"name"`
	Content    string    `json:"content"`
	MailNotify OptString `json:"mailNotify"`
}

// GetProjectId returns the value of ProjectId.
func (s *CreateWikiReq) GetProjectId() int {
	return s.ProjectId
}

// GetName returns the value of Name.
func (s *CreateWikiReq) GetName() string {
	return s.Name
}

// GetContent returns the value of Content.
func (s *CreateWikiReq) GetContent() string {
	return s.Content
}

// GetMailNotify returns the value of MailNotify.
func (s *CreateWikiReq) GetMailNotify() OptString {
	return s.MailNotify
}

// SetProjectId sets the value of ProjectId.
func (s *CreateWikiReq) SetProjectId(val int) {
	s.ProjectId = val
}

// SetName sets the value of Name.
func (s *CreateWikiReq) SetName(val string) {
	s.Name = val
}

// SetContent sets the value of Content.
func (s *CreateWikiReq) SetContent(val string) {
	s.Content = val
}

// SetMailNotify sets the value of MailNotify.
func (s *CreateWikiReq) SetMailNotify(val OptString) {
	s.MailNotify = val
}

type GetCommentsCountOK struct {
	Count OptInt `json:"count"`
}

// GetCount returns the value of Count.
func (s *GetCommentsCountOK) GetCount() OptInt {
	return s.Count
}

// SetCount sets the value of Count.
func (s *GetCommentsCountOK) SetCount(val OptInt) {
	s.Count = val
}

type GetIssuesCountOK struct {
	Count OptInt `json:"count"`
}

// GetCount returns the value of Count.
func (s *GetIssuesCountOK) GetCount() OptInt {
	return s.Count
}

// SetCount sets the value of Count.
func (s *GetIssuesCountOK) SetCount(val OptInt) {
	s.Count = val
}

type GetPullRequestsCountOK struct {
	Count OptInt `json:"count"`
}

// GetCount returns the value of Count.
func (s *GetPullRequestsCountOK) GetCount() OptInt {
	return s.Count
}

// SetCount sets the value of Count.
func (s *GetPullRequestsCountOK) SetCount(val OptInt) {
	s.Count = val
}

type GetWikisCountOK struct {
	Count OptInt `json:"count"`
}

// GetCount returns the value of Count.
func (s *GetWikisCountOK) GetCount() OptInt {
	return s.Count
}

// SetCount sets the value of Count.
func (s *GetWikisCountOK) SetCount(val OptInt) {
	s.Count = val
}

// Ref: #/components/schemas/Issue
type Issue struct {
	ID             OptInt           `json:"id"`
	ProjectId      OptInt           `json:"projectId"`
	IssueKey       OptString        `json:"issueKey"`
	KeyId          OptInt           `json:"keyId"`
	IssueType      OptIssueType     `json:"issueType"`
	Summary        OptString        `json:"summary"`
	Description    OptString        `json:"description"`
	Resolution     OptNilResolution `json:"resolution"`
	Priority       OptPriority      `json:"priority"`
	Status         OptStatus        `json:"status"`
	Assignee       OptNilUser       `json:"assignee"`
	Category       []Category       `json:"category"`
	Versions       []Version        `json:"versions"`
	Milestone      []Version        `json:"milestone"`
	StartDate      OptNilString     `json:"startDate"`
	DueDate        OptNilString     `json:"dueDate"`
	EstimatedHours OptNilFloat64    `json:"estimatedHours"`
	ActualHours    OptNilFloat64    `json:"actualHours"`
	ParentIssueId  OptNilInt        `json:"parentIssueId"`
	CreatedUser    OptUser          `json:"createdUser"`
	Created        OptString        `json:"created"`
	UpdatedUser    OptUser          `json:"updatedUser"`
	Updated        OptString        `json:"updated"`
	Attachments    []Attachment     `json:"attachments"`
	SharedFiles    []SharedFile     `json:"sharedFiles"`
	Stars          []Star           `json:"stars"`
}

// GetID returns the value of ID.
func (s *Issue) GetID() OptInt {
	return s.ID
}

// GetProjectId returns the value of ProjectId.
func (s *Issue) GetProjectId() OptInt {
	return s.ProjectId
}

// GetIssueKey returns the value of IssueKey.
func (s *Issue) GetIssueKey() OptString {
	return s.IssueKey
}

// GetKeyId returns the value of KeyId.
func (s *Issue) GetKeyId() OptInt {
	return s.KeyId
}

// GetIssueType returns the value of IssueType.
func (s *Issue) GetIssueType() OptIssueType {
	return s.IssueType
}

// GetSummary returns the value of Summary.
func (s *Issue) GetSummary() OptString {
	return s.Summary
}

// GetDescription returns the value of Description.
func (s *Issue) GetDescription() OptString {
	return s.Description
}

// GetResolution returns the value of Resolution.
func (s *Issue) GetResolution() OptNilResolution {
	return s.Resolution
}

// GetPriority returns the value of Priority.
func (s *Issue) GetPriority() OptPriority {
	return s.Priority
}

// GetStatus returns the value of Status.
func (s *Issue) GetStatus() OptStatus {
	return s.Status
}

// GetAssignee returns the value of Assignee.
func (s *Issue) GetAssignee() OptNilUser {
	return s.Assignee
}

// GetCategory returns the value of Category.
func (s *Issue) GetCategory() []Category {
	return s.Category
}

// GetVersions returns the value of Versions.
func (s *Issue) GetVersions() []Version {
	return s.Versions
}

// GetMilestone returns the value of Milestone.
func (s *Issue) GetMilestone() []Version {
	return s.Milestone
}

// GetStartDate returns the value of StartDate.
func (s *Issue) GetStartDate() OptNilString {
	return s.StartDate
}

// GetDueDate returns the value of DueDate.
func (s *Issue) GetDueDate() OptNilString {
	return s.DueDate
}

// GetEstimatedHours returns the value of EstimatedHours.
func (s *Issue) GetEstimatedHours() OptNilFloat64 {
	return s.EstimatedHours
}

// GetActualHours returns the value of ActualHours.
func (s *Issue) GetActualHours() OptNilFloat64 {
	return s.ActualHours
}

// GetParentIssueId returns the value of ParentIssueId.
func (s *Issue) GetParentIssueId() OptNilInt {
	return s.ParentIssueId
}

// GetCreatedUser returns the value of CreatedUser.
func (s *Issue) GetCreatedUser() OptUser {
	return s.CreatedUser
}

// GetCreated returns the value of Created.
func (s *Issue) GetCreated() OptString {
	return s.Created
}

// GetUpdatedUser returns the value of UpdatedUser.
func (s *Issue) GetUpdatedUser() OptUser {
	return s.UpdatedUser
}

// GetUpdated returns the value of Updated.
func (s *Issue) GetUpdated() OptString {
	return s.Updated
}

// GetAttachments returns the value of Attachments.
func (s *Issue) GetAttachments() []Attachment {
	return s.Attachments
}

// GetSharedFiles returns the value of SharedFiles.
func (s *Issue) GetSharedFiles() []SharedFile {
	return s.SharedFiles
}

// GetStars returns the value of Stars.
func (s *Issue) GetStars() []Star {
	return s.Stars
}

// SetID sets the value of ID.
func (s *Issue) SetID(val OptInt) {
	s.ID = val
}

// SetProjectId sets the value of ProjectId.
func (s *Issue) SetProjectId(val OptInt) {
	s.ProjectId = val
}

// SetIssueKey sets the value of IssueKey.
func (s *Issue) SetIssueKey(val OptString) {
	s.IssueKey = val
}

// SetKeyId sets the value of KeyId.
func (s *Issue) SetKeyId(val OptInt) {
	s.KeyId = val
}

// SetIssueType sets the value of IssueType.
func (s *Issue) SetIssueType(val OptIssueType) {
	s.IssueType = val
}

// SetSummary sets the value of Summary.
func (s *Issue) SetSummary(val OptString) {
	s.Summary = val
}

// SetDescription sets the value of Description.
func (s *Issue) SetDescription(val OptString) {
	s.Description = val
}

// SetResolution sets the value of Resolution.
func (s *Issue) SetResolution(val OptNilResolution) {
	s.Resolution = val
}

// SetPriority sets the value of Priority.
func (s *Issue) SetPriority(val OptPriority) {
	s.Priority = val
}

// SetStatus sets the value of Status.
func (s *Issue) SetStatus(val OptStatus) {
	s.Status = val
}

// SetAssignee sets the value of Assignee.
func (s *Issue) SetAssignee(val OptNilUser) {
	s.Assignee = val
}

// SetCategory sets the value of Category.
func (s *Issue) SetCategory(val []Category) {
	s.Category = val
}

// SetVersions sets the value of Versions.
func (s *Issue) SetVersions(val []Version) {
	s.Versions = val
}

// SetMilestone sets the value of Milestone.
func (s *Issue) SetMilestone(val []Version) {
	s.Milestone = val
}

// SetStartDate sets the value of StartDate.
func (s *Issue) SetStartDate(val OptNilString) {
	s.StartDate = val
}

// SetDueDate sets the value of DueDate.
func (s *Issue) SetDueDate(val OptNilString) {
	s.DueDate = val
}

// SetEstimatedHours sets the value of EstimatedHours.
func (s *Issue) SetEstimatedHours(val OptNilFloat64) {
	s.EstimatedHours = val
}

// SetActualHours sets the value of ActualHours.
func (s *Issue) SetActualHours(val OptNilFloat64) {
	s.ActualHours = val
}

// SetParentIssueId sets the value of ParentIssueId.
func (s *Issue) SetParentIssueId(val OptNilInt) {
	s.ParentIssueId = val
}

// SetCreatedUser sets the value of CreatedUser.
func (s *Issue) SetCreatedUser(val OptUser) {
	s.CreatedUser = val
}

// SetCreated sets the value of Created.
func (s *Issue) SetCreated(val OptString) {
	s.Created = val
}

// SetUpdatedUser sets the value of UpdatedUser.
func (s *Issue) SetUpdatedUser(val OptUser) {
	s.UpdatedUser = val
}

// SetUpdated sets the value of Updated.
func (s *Issue) SetUpdated(val OptString) {
	s.Updated = val
}

// SetAttachments sets the value of Attachments.
func (s *Issue) SetAttachments(val []Attachment) {
	s.Attachments = val
}

// SetSharedFiles sets the value of SharedFiles.
func (s *Issue) SetSharedFiles(val []SharedFile) {
	s.SharedFiles = val
}

// SetStars sets the value of Stars.
func (s *Issue) SetStars(val []Star) {
	s.Stars = val
}

// Ref: #/components/schemas/IssueType
type IssueType struct {
	ID           OptInt    `json:"id"`
	ProjectId    OptInt    `json:"projectId"`
	Name         OptString `json:"name"`
	Color        OptString `json:"color"`
	DisplayOrder OptInt    `json:"displayOrder"`
}

// GetID returns the value of ID.
func (s *IssueType) GetID() OptInt {
	return s.ID
}

// GetProjectId returns the value of ProjectId.
func (s *IssueType) GetProjectId() OptInt {
	return s.ProjectId
}

// GetName returns the value of Name.
func (s *IssueType) GetName() OptString {
	return s.Name
}

// GetColor returns the value of Color.
func (s *IssueType) GetColor() OptString {
	return s.Color
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *IssueType) GetDisplayOrder() OptInt {
	return s.DisplayOrder
}

// SetID sets the value of ID.
func (s *IssueType) SetID(val OptInt) {
	s.ID = val
}

// SetProjectId sets the value of ProjectId.
func (s *IssueType) SetProjectId(val OptInt) {
	s.ProjectId = val
}

// SetName sets the value of Name.
func (s *IssueType) SetName(val OptString) {
	s.Name = val
}

// SetColor sets the value of Color.
func (s *IssueType) SetColor(val OptString) {
	s.Color = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *IssueType) SetDisplayOrder(val OptInt) {
	s.DisplayOrder = val
}

// Ref: #/components/schemas/Notification
type Notification struct {
	ID                  OptInt  `json:"id"`
	AlreadyRead         OptBool `json:"alreadyRead"`
	Reason              OptInt  `json:"reason"`
	User                OptUser `json:"user"`
	ResourceAlreadyRead OptBool `json:"resourceAlreadyRead"`
}

// GetID returns the value of ID.
func (s *Notification) GetID() OptInt {
	return s.ID
}

// GetAlreadyRead returns the value of AlreadyRead.
func (s *Notification) GetAlreadyRead() OptBool {
	return s.AlreadyRead
}

// GetReason returns the value of Reason.
func (s *Notification) GetReason() OptInt {
	return s.Reason
}

// GetUser returns the value of User.
func (s *Notification) GetUser() OptUser {
	return s.User
}

// GetResourceAlreadyRead returns the value of ResourceAlreadyRead.
func (s *Notification) GetResourceAlreadyRead() OptBool {
	return s.ResourceAlreadyRead
}

// SetID sets the value of ID.
func (s *Notification) SetID(val OptInt) {
	s.ID = val
}

// SetAlreadyRead sets the value of AlreadyRead.
func (s *Notification) SetAlreadyRead(val OptBool) {
	s.AlreadyRead = val
}

// SetReason sets the value of Reason.
func (s *Notification) SetReason(val OptInt) {
	s.Reason = val
}

// SetUser sets the value of User.
func (s *Notification) SetUser(val OptUser) {
	s.User = val
}

// SetResourceAlreadyRead sets the value of ResourceAlreadyRead.
func (s *Notification) SetResourceAlreadyRead(val OptBool) {
	s.ResourceAlreadyRead = val
}

// Ref: #/components/schemas/NulabAccount
type NulabAccount struct {
	NulabId  OptString `json:"nulabId"`
	Name     OptString `json:"name"`
	UniqueId OptString `json:"uniqueId"`
}

// GetNulabId returns the value of NulabId.
func (s *NulabAccount) GetNulabId() OptString {
	return s.NulabId
}

// GetName returns the value of Name.
func (s *NulabAccount) GetName() OptString {
	return s.Name
}

// GetUniqueId returns the value of UniqueId.
func (s *NulabAccount) GetUniqueId() OptString {
	return s.UniqueId
}

// SetNulabId sets the value of NulabId.
func (s *NulabAccount) SetNulabId(val OptString) {
	s.NulabId = val
}

// SetName sets the value of Name.
func (s *NulabAccount) SetName(val OptString) {
	s.Name = val
}

// SetUniqueId sets the value of UniqueId.
func (s *NulabAccount) SetUniqueId(val OptString) {
	s.UniqueId = val
}

type OAuth2 struct {
	Token  string
	Scopes []string
}

// GetToken returns the value of Token.
func (s *OAuth2) GetToken() string {
	return s.Token
}

// GetScopes returns the value of Scopes.
func (s *OAuth2) GetScopes() []string {
	return s.Scopes
}

// SetToken sets the value of Token.
func (s *OAuth2) SetToken(val string) {
	s.Token = val
}

// SetScopes sets the value of Scopes.
func (s *OAuth2) SetScopes(val []string) {
	s.Scopes = val
}

// NewOptAddCommentReq returns new OptAddCommentReq with value set to v.
func NewOptAddCommentReq(v AddCommentReq) OptAddCommentReq {
	return OptAddCommentReq{
		Value: v,
		Set:   true,
	}
}

// OptAddCommentReq is optional AddCommentReq.
type OptAddCommentReq struct {
	Value AddCommentReq
	Set   bool
}

// IsSet returns true if OptAddCommentReq was set.
func (o OptAddCommentReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAddCommentReq) Reset() {
	var v AddCommentReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAddCommentReq) SetTo(v AddCommentReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAddCommentReq) Get() (v AddCommentReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAddCommentReq) Or(d AddCommentReq) AddCommentReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateIssueReq returns new OptCreateIssueReq with value set to v.
func NewOptCreateIssueReq(v CreateIssueReq) OptCreateIssueReq {
	return OptCreateIssueReq{
		Value: v,
		Set:   true,
	}
}

// OptCreateIssueReq is optional CreateIssueReq.
type OptCreateIssueReq struct {
	Value CreateIssueReq
	Set   bool
}

// IsSet returns true if OptCreateIssueReq was set.
func (o OptCreateIssueReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateIssueReq) Reset() {
	var v CreateIssueReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateIssueReq) SetTo(v CreateIssueReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateIssueReq) Get() (v CreateIssueReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateIssueReq) Or(d CreateIssueReq) CreateIssueReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateWikiReq returns new OptCreateWikiReq with value set to v.
func NewOptCreateWikiReq(v CreateWikiReq) OptCreateWikiReq {
	return OptCreateWikiReq{
		Value: v,
		Set:   true,
	}
}

// OptCreateWikiReq is optional CreateWikiReq.
type OptCreateWikiReq struct {
	Value CreateWikiReq
	Set   bool
}

// IsSet returns true if OptCreateWikiReq was set.
func (o OptCreateWikiReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateWikiReq) Reset() {
	var v CreateWikiReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateWikiReq) SetTo(v CreateWikiReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateWikiReq) Get() (v CreateWikiReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateWikiReq) Or(d CreateWikiReq) CreateWikiReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptIssue returns new OptIssue with value set to v.
func NewOptIssue(v Issue) OptIssue {
	return OptIssue{
		Value: v,
		Set:   true,
	}
}

// OptIssue is optional Issue.
type OptIssue struct {
	Value Issue
	Set   bool
}

// IsSet returns true if OptIssue was set.
func (o OptIssue) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptIssue) Reset() {
	var v Issue
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptIssue) SetTo(v Issue) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptIssue) Get() (v Issue, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptIssue) Or(d Issue) Issue {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptIssueType returns new OptIssueType with value set to v.
func NewOptIssueType(v IssueType) OptIssueType {
	return OptIssueType{
		Value: v,
		Set:   true,
	}
}

// OptIssueType is optional IssueType.
type OptIssueType struct {
	Value IssueType
	Set   bool
}

// IsSet returns true if OptIssueType was set.
func (o OptIssueType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptIssueType) Reset() {
	var v IssueType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptIssueType) SetTo(v IssueType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptIssueType) Get() (v IssueType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptIssueType) Or(d IssueType) IssueType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilFloat64 returns new OptNilFloat64 with value set to v.
func NewOptNilFloat64(v float64) OptNilFloat64 {
	return OptNilFloat64{
		Value: v,
		Set:   true,
	}
}

// OptNilFloat64 is optional nullable float64.
type OptNilFloat64 struct {
	Value float64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilFloat64 was set.
func (o OptNilFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilFloat64) SetTo(v float64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilFloat64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilFloat64) SetToNull() {
	o.Set = true
	o.Null = true
	var v float64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilFloat64) Get() (v float64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt returns new OptNilInt with value set to v.
func NewOptNilInt(v int) OptNilInt {
	return OptNilInt{
		Value: v,
		Set:   true,
	}
}

// OptNilInt is optional nullable int.
type OptNilInt struct {
	Value int
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt was set.
func (o OptNilInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt) SetTo(v int) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt) SetToNull() {
	o.Set = true
	o.Null = true
	var v int
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilResolution returns new OptNilResolution with value set to v.
func NewOptNilResolution(v Resolution) OptNilResolution {
	return OptNilResolution{
		Value: v,
		Set:   true,
	}
}

// OptNilResolution is optional nullable Resolution.
type OptNilResolution struct {
	Value Resolution
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilResolution was set.
func (o OptNilResolution) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilResolution) Reset() {
	var v Resolution
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilResolution) SetTo(v Resolution) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilResolution) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilResolution) SetToNull() {
	o.Set = true
	o.Null = true
	var v Resolution
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilResolution) Get() (v Resolution, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilResolution) Or(d Resolution) Resolution {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUser returns new OptNilUser with value set to v.
func NewOptNilUser(v User) OptNilUser {
	return OptNilUser{
		Value: v,
		Set:   true,
	}
}

// OptNilUser is optional nullable User.
type OptNilUser struct {
	Value User
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUser was set.
func (o OptNilUser) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUser) Reset() {
	var v User
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUser) SetTo(v User) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUser) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUser) SetToNull() {
	o.Set = true
	o.Null = true
	var v User
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUser) Get() (v User, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUser) Or(d User) User {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNulabAccount returns new OptNulabAccount with value set to v.
func NewOptNulabAccount(v NulabAccount) OptNulabAccount {
	return OptNulabAccount{
		Value: v,
		Set:   true,
	}
}

// OptNulabAccount is optional NulabAccount.
type OptNulabAccount struct {
	Value NulabAccount
	Set   bool
}

// IsSet returns true if OptNulabAccount was set.
func (o OptNulabAccount) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNulabAccount) Reset() {
	var v NulabAccount
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptNulabAccount) SetTo(v NulabAccount) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNulabAccount) Get() (v NulabAccount, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNulabAccount) Or(d NulabAccount) NulabAccount {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPRStatus returns new OptPRStatus with value set to v.
func NewOptPRStatus(v PRStatus) OptPRStatus {
	return OptPRStatus{
		Value: v,
		Set:   true,
	}
}

// OptPRStatus is optional PRStatus.
type OptPRStatus struct {
	Value PRStatus
	Set   bool
}

// IsSet returns true if OptPRStatus was set.
func (o OptPRStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPRStatus) Reset() {
	var v PRStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPRStatus) SetTo(v PRStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPRStatus) Get() (v PRStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPRStatus) Or(d PRStatus) PRStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPriority returns new OptPriority with value set to v.
func NewOptPriority(v Priority) OptPriority {
	return OptPriority{
		Value: v,
		Set:   true,
	}
}

// OptPriority is optional Priority.
type OptPriority struct {
	Value Priority
	Set   bool
}

// IsSet returns true if OptPriority was set.
func (o OptPriority) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPriority) Reset() {
	var v Priority
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPriority) SetTo(v Priority) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPriority) Get() (v Priority, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPriority) Or(d Priority) Priority {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptStatus returns new OptStatus with value set to v.
func NewOptStatus(v Status) OptStatus {
	return OptStatus{
		Value: v,
		Set:   true,
	}
}

// OptStatus is optional Status.
type OptStatus struct {
	Value Status
	Set   bool
}

// IsSet returns true if OptStatus was set.
func (o OptStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptStatus) Reset() {
	var v Status
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptStatus) SetTo(v Status) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptStatus) Get() (v Status, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptStatus) Or(d Status) Status {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateCommentReq returns new OptUpdateCommentReq with value set to v.
func NewOptUpdateCommentReq(v UpdateCommentReq) OptUpdateCommentReq {
	return OptUpdateCommentReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdateCommentReq is optional UpdateCommentReq.
type OptUpdateCommentReq struct {
	Value UpdateCommentReq
	Set   bool
}

// IsSet returns true if OptUpdateCommentReq was set.
func (o OptUpdateCommentReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateCommentReq) Reset() {
	var v UpdateCommentReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateCommentReq) SetTo(v UpdateCommentReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateCommentReq) Get() (v UpdateCommentReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateCommentReq) Or(d UpdateCommentReq) UpdateCommentReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateIssueReq returns new OptUpdateIssueReq with value set to v.
func NewOptUpdateIssueReq(v UpdateIssueReq) OptUpdateIssueReq {
	return OptUpdateIssueReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdateIssueReq is optional UpdateIssueReq.
type OptUpdateIssueReq struct {
	Value UpdateIssueReq
	Set   bool
}

// IsSet returns true if OptUpdateIssueReq was set.
func (o OptUpdateIssueReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateIssueReq) Reset() {
	var v UpdateIssueReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateIssueReq) SetTo(v UpdateIssueReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateIssueReq) Get() (v UpdateIssueReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateIssueReq) Or(d UpdateIssueReq) UpdateIssueReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateWikiReq returns new OptUpdateWikiReq with value set to v.
func NewOptUpdateWikiReq(v UpdateWikiReq) OptUpdateWikiReq {
	return OptUpdateWikiReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdateWikiReq is optional UpdateWikiReq.
type OptUpdateWikiReq struct {
	Value UpdateWikiReq
	Set   bool
}

// IsSet returns true if OptUpdateWikiReq was set.
func (o OptUpdateWikiReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateWikiReq) Reset() {
	var v UpdateWikiReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateWikiReq) SetTo(v UpdateWikiReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateWikiReq) Get() (v UpdateWikiReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateWikiReq) Or(d UpdateWikiReq) UpdateWikiReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUser returns new OptUser with value set to v.
func NewOptUser(v User) OptUser {
	return OptUser{
		Value: v,
		Set:   true,
	}
}

// OptUser is optional User.
type OptUser struct {
	Value User
	Set   bool
}

// IsSet returns true if OptUser was set.
func (o OptUser) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUser) Reset() {
	var v User
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUser) SetTo(v User) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUser) Get() (v User, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUser) Or(d User) User {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PRStatus
type PRStatus struct {
	ID   OptInt    `json:"id"`
	Name OptString `json:"name"`
}

// GetID returns the value of ID.
func (s *PRStatus) GetID() OptInt {
	return s.ID
}

// GetName returns the value of Name.
func (s *PRStatus) GetName() OptString {
	return s.Name
}

// SetID sets the value of ID.
func (s *PRStatus) SetID(val OptInt) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *PRStatus) SetName(val OptString) {
	s.Name = val
}

// Ref: #/components/schemas/Priority
type Priority struct {
	ID   OptInt    `json:"id"`
	Name OptString `json:"name"`
}

// GetID returns the value of ID.
func (s *Priority) GetID() OptInt {
	return s.ID
}

// GetName returns the value of Name.
func (s *Priority) GetName() OptString {
	return s.Name
}

// SetID sets the value of ID.
func (s *Priority) SetID(val OptInt) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Priority) SetName(val OptString) {
	s.Name = val
}

// Ref: #/components/schemas/Project
type Project struct {
	ID                                OptInt    `json:"id"`
	ProjectKey                        OptString `json:"projectKey"`
	Name                              OptString `json:"name"`
	ChartEnabled                      OptBool   `json:"chartEnabled"`
	UseResolvedForChart               OptBool   `json:"useResolvedForChart"`
	SubtaskingEnabled                 OptBool   `json:"subtaskingEnabled"`
	ProjectLeaderCanEditProjectLeader OptBool   `json:"projectLeaderCanEditProjectLeader"`
	UseWiki                           OptBool   `json:"useWiki"`
	UseFileSharing                    OptBool   `json:"useFileSharing"`
	UseWikiTreeView                   OptBool   `json:"useWikiTreeView"`
	UseOriginalImageSizeAtWiki        OptBool   `json:"useOriginalImageSizeAtWiki"`
	TextFormattingRule                OptString `json:"textFormattingRule"`
	Archived                          OptBool   `json:"archived"`
	DisplayOrder                      OptInt    `json:"displayOrder"`
	UseDevAttributes                  OptBool   `json:"useDevAttributes"`
}

// GetID returns the value of ID.
func (s *Project) GetID() OptInt {
	return s.ID
}

// GetProjectKey returns the value of ProjectKey.
func (s *Project) GetProjectKey() OptString {
	return s.ProjectKey
}

// GetName returns the value of Name.
func (s *Project) GetName() OptString {
	return s.Name
}

// GetChartEnabled returns the value of ChartEnabled.
func (s *Project) GetChartEnabled() OptBool {
	return s.ChartEnabled
}

// GetUseResolvedForChart returns the value of UseResolvedForChart.
func (s *Project) GetUseResolvedForChart() OptBool {
	return s.UseResolvedForChart
}

// GetSubtaskingEnabled returns the value of SubtaskingEnabled.
func (s *Project) GetSubtaskingEnabled() OptBool {
	return s.SubtaskingEnabled
}

// GetProjectLeaderCanEditProjectLeader returns the value of ProjectLeaderCanEditProjectLeader.
func (s *Project) GetProjectLeaderCanEditProjectLeader() OptBool {
	return s.ProjectLeaderCanEditProjectLeader
}

// GetUseWiki returns the value of UseWiki.
func (s *Project) GetUseWiki() OptBool {
	return s.UseWiki
}

// GetUseFileSharing returns the value of UseFileSharing.
func (s *Project) GetUseFileSharing() OptBool {
	return s.UseFileSharing
}

// GetUseWikiTreeView returns the value of UseWikiTreeView.
func (s *Project) GetUseWikiTreeView() OptBool {
	return s.UseWikiTreeView
}

// GetUseOriginalImageSizeAtWiki returns the value of UseOriginalImageSizeAtWiki.
func (s *Project) GetUseOriginalImageSizeAtWiki() OptBool {
	return s.UseOriginalImageSizeAtWiki
}

// GetTextFormattingRule returns the value of TextFormattingRule.
func (s *Project) GetTextFormattingRule() OptString {
	return s.TextFormattingRule
}

// GetArchived returns the value of Archived.
func (s *Project) GetArchived() OptBool {
	return s.Archived
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *Project) GetDisplayOrder() OptInt {
	return s.DisplayOrder
}

// GetUseDevAttributes returns the value of UseDevAttributes.
func (s *Project) GetUseDevAttributes() OptBool {
	return s.UseDevAttributes
}

// SetID sets the value of ID.
func (s *Project) SetID(val OptInt) {
	s.ID = val
}

// SetProjectKey sets the value of ProjectKey.
func (s *Project) SetProjectKey(val OptString) {
	s.ProjectKey = val
}

// SetName sets the value of Name.
func (s *Project) SetName(val OptString) {
	s.Name = val
}

// SetChartEnabled sets the value of ChartEnabled.
func (s *Project) SetChartEnabled(val OptBool) {
	s.ChartEnabled = val
}

// SetUseResolvedForChart sets the value of UseResolvedForChart.
func (s *Project) SetUseResolvedForChart(val OptBool) {
	s.UseResolvedForChart = val
}

// SetSubtaskingEnabled sets the value of SubtaskingEnabled.
func (s *Project) SetSubtaskingEnabled(val OptBool) {
	s.SubtaskingEnabled = val
}

// SetProjectLeaderCanEditProjectLeader sets the value of ProjectLeaderCanEditProjectLeader.
func (s *Project) SetProjectLeaderCanEditProjectLeader(val OptBool) {
	s.ProjectLeaderCanEditProjectLeader = val
}

// SetUseWiki sets the value of UseWiki.
func (s *Project) SetUseWiki(val OptBool) {
	s.UseWiki = val
}

// SetUseFileSharing sets the value of UseFileSharing.
func (s *Project) SetUseFileSharing(val OptBool) {
	s.UseFileSharing = val
}

// SetUseWikiTreeView sets the value of UseWikiTreeView.
func (s *Project) SetUseWikiTreeView(val OptBool) {
	s.UseWikiTreeView = val
}

// SetUseOriginalImageSizeAtWiki sets the value of UseOriginalImageSizeAtWiki.
func (s *Project) SetUseOriginalImageSizeAtWiki(val OptBool) {
	s.UseOriginalImageSizeAtWiki = val
}

// SetTextFormattingRule sets the value of TextFormattingRule.
func (s *Project) SetTextFormattingRule(val OptString) {
	s.TextFormattingRule = val
}

// SetArchived sets the value of Archived.
func (s *Project) SetArchived(val OptBool) {
	s.Archived = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *Project) SetDisplayOrder(val OptInt) {
	s.DisplayOrder = val
}

// SetUseDevAttributes sets the value of UseDevAttributes.
func (s *Project) SetUseDevAttributes(val OptBool) {
	s.UseDevAttributes = val
}

// Ref: #/components/schemas/PullRequest
type PullRequest struct {
	ID           OptInt       `json:"id"`
	ProjectId    OptInt       `json:"projectId"`
	RepositoryId OptInt       `json:"repositoryId"`
	Number       OptInt       `json:"number"`
	Summary      OptString    `json:"summary"`
	Description  OptString    `json:"description"`
	Base         OptString    `json:"base"`
	Branch       OptString    `json:"branch"`
	Status       OptPRStatus  `json:"status"`
	Assignee     OptUser      `json:"assignee"`
	Issue        OptIssue     `json:"issue"`
	BaseCommit   OptString    `json:"baseCommit"`
	BranchCommit OptString    `json:"branchCommit"`
	CloseAt      OptNilString `json:"closeAt"`
	MergeAt      OptNilString `json:"mergeAt"`
	CreatedUser  OptUser      `json:"createdUser"`
	Created      OptString    `json:"created"`
	UpdatedUser  OptUser      `json:"updatedUser"`
	Updated      OptString    `json:"updated"`
}

// GetID returns the value of ID.
func (s *PullRequest) GetID() OptInt {
	return s.ID
}

// GetProjectId returns the value of ProjectId.
func (s *PullRequest) GetProjectId() OptInt {
	return s.ProjectId
}

// GetRepositoryId returns the value of RepositoryId.
func (s *PullRequest) GetRepositoryId() OptInt {
	return s.RepositoryId
}

// GetNumber returns the value of Number.
func (s *PullRequest) GetNumber() OptInt {
	return s.Number
}

// GetSummary returns the value of Summary.
func (s *PullRequest) GetSummary() OptString {
	return s.Summary
}

// GetDescription returns the value of Description.
func (s *PullRequest) GetDescription() OptString {
	return s.Description
}

// GetBase returns the value of Base.
func (s *PullRequest) GetBase() OptString {
	return s.Base
}

// GetBranch returns the value of Branch.
func (s *PullRequest) GetBranch() OptString {
	return s.Branch
}

// GetStatus returns the value of Status.
func (s *PullRequest) GetStatus() OptPRStatus {
	return s.Status
}

// GetAssignee returns the value of Assignee.
func (s *PullRequest) GetAssignee() OptUser {
	return s.Assignee
}

// GetIssue returns the value of Issue.
func (s *PullRequest) GetIssue() OptIssue {
	return s.Issue
}

// GetBaseCommit returns the value of BaseCommit.
func (s *PullRequest) GetBaseCommit() OptString {
	return s.BaseCommit
}

// GetBranchCommit returns the value of BranchCommit.
func (s *PullRequest) GetBranchCommit() OptString {
	return s.BranchCommit
}

// GetCloseAt returns the value of CloseAt.
func (s *PullRequest) GetCloseAt() OptNilString {
	return s.CloseAt
}

// GetMergeAt returns the value of MergeAt.
func (s *PullRequest) GetMergeAt() OptNilString {
	return s.MergeAt
}

// GetCreatedUser returns the value of CreatedUser.
func (s *PullRequest) GetCreatedUser() OptUser {
	return s.CreatedUser
}

// GetCreated returns the value of Created.
func (s *PullRequest) GetCreated() OptString {
	return s.Created
}

// GetUpdatedUser returns the value of UpdatedUser.
func (s *PullRequest) GetUpdatedUser() OptUser {
	return s.UpdatedUser
}

// GetUpdated returns the value of Updated.
func (s *PullRequest) GetUpdated() OptString {
	return s.Updated
}

// SetID sets the value of ID.
func (s *PullRequest) SetID(val OptInt) {
	s.ID = val
}

// SetProjectId sets the value of ProjectId.
func (s *PullRequest) SetProjectId(val OptInt) {
	s.ProjectId = val
}

// SetRepositoryId sets the value of RepositoryId.
func (s *PullRequest) SetRepositoryId(val OptInt) {
	s.RepositoryId = val
}

// SetNumber sets the value of Number.
func (s *PullRequest) SetNumber(val OptInt) {
	s.Number = val
}

// SetSummary sets the value of Summary.
func (s *PullRequest) SetSummary(val OptString) {
	s.Summary = val
}

// SetDescription sets the value of Description.
func (s *PullRequest) SetDescription(val OptString) {
	s.Description = val
}

// SetBase sets the value of Base.
func (s *PullRequest) SetBase(val OptString) {
	s.Base = val
}

// SetBranch sets the value of Branch.
func (s *PullRequest) SetBranch(val OptString) {
	s.Branch = val
}

// SetStatus sets the value of Status.
func (s *PullRequest) SetStatus(val OptPRStatus) {
	s.Status = val
}

// SetAssignee sets the value of Assignee.
func (s *PullRequest) SetAssignee(val OptUser) {
	s.Assignee = val
}

// SetIssue sets the value of Issue.
func (s *PullRequest) SetIssue(val OptIssue) {
	s.Issue = val
}

// SetBaseCommit sets the value of BaseCommit.
func (s *PullRequest) SetBaseCommit(val OptString) {
	s.BaseCommit = val
}

// SetBranchCommit sets the value of BranchCommit.
func (s *PullRequest) SetBranchCommit(val OptString) {
	s.BranchCommit = val
}

// SetCloseAt sets the value of CloseAt.
func (s *PullRequest) SetCloseAt(val OptNilString) {
	s.CloseAt = val
}

// SetMergeAt sets the value of MergeAt.
func (s *PullRequest) SetMergeAt(val OptNilString) {
	s.MergeAt = val
}

// SetCreatedUser sets the value of CreatedUser.
func (s *PullRequest) SetCreatedUser(val OptUser) {
	s.CreatedUser = val
}

// SetCreated sets the value of Created.
func (s *PullRequest) SetCreated(val OptString) {
	s.Created = val
}

// SetUpdatedUser sets the value of UpdatedUser.
func (s *PullRequest) SetUpdatedUser(val OptUser) {
	s.UpdatedUser = val
}

// SetUpdated sets the value of Updated.
func (s *PullRequest) SetUpdated(val OptString) {
	s.Updated = val
}

// Ref: #/components/schemas/Repository
type Repository struct {
	ID           OptInt       `json:"id"`
	ProjectId    OptInt       `json:"projectId"`
	Name         OptString    `json:"name"`
	Description  OptNilString `json:"description"`
	HookUrl      OptNilString `json:"hookUrl"`
	HttpUrl      OptString    `json:"httpUrl"`
	SshUrl       OptString    `json:"sshUrl"`
	DisplayOrder OptInt       `json:"displayOrder"`
	PushedAt     OptNilString `json:"pushedAt"`
	CreatedUser  OptUser      `json:"createdUser"`
	Created      OptString    `json:"created"`
	UpdatedUser  OptUser      `json:"updatedUser"`
	Updated      OptString    `json:"updated"`
}

// GetID returns the value of ID.
func (s *Repository) GetID() OptInt {
	return s.ID
}

// GetProjectId returns the value of ProjectId.
func (s *Repository) GetProjectId() OptInt {
	return s.ProjectId
}

// GetName returns the value of Name.
func (s *Repository) GetName() OptString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Repository) GetDescription() OptNilString {
	return s.Description
}

// GetHookUrl returns the value of HookUrl.
func (s *Repository) GetHookUrl() OptNilString {
	return s.HookUrl
}

// GetHttpUrl returns the value of HttpUrl.
func (s *Repository) GetHttpUrl() OptString {
	return s.HttpUrl
}

// GetSshUrl returns the value of SshUrl.
func (s *Repository) GetSshUrl() OptString {
	return s.SshUrl
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *Repository) GetDisplayOrder() OptInt {
	return s.DisplayOrder
}

// GetPushedAt returns the value of PushedAt.
func (s *Repository) GetPushedAt() OptNilString {
	return s.PushedAt
}

// GetCreatedUser returns the value of CreatedUser.
func (s *Repository) GetCreatedUser() OptUser {
	return s.CreatedUser
}

// GetCreated returns the value of Created.
func (s *Repository) GetCreated() OptString {
	return s.Created
}

// GetUpdatedUser returns the value of UpdatedUser.
func (s *Repository) GetUpdatedUser() OptUser {
	return s.UpdatedUser
}

// GetUpdated returns the value of Updated.
func (s *Repository) GetUpdated() OptString {
	return s.Updated
}

// SetID sets the value of ID.
func (s *Repository) SetID(val OptInt) {
	s.ID = val
}

// SetProjectId sets the value of ProjectId.
func (s *Repository) SetProjectId(val OptInt) {
	s.ProjectId = val
}

// SetName sets the value of Name.
func (s *Repository) SetName(val OptString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Repository) SetDescription(val OptNilString) {
	s.Description = val
}

// SetHookUrl sets the value of HookUrl.
func (s *Repository) SetHookUrl(val OptNilString) {
	s.HookUrl = val
}

// SetHttpUrl sets the value of HttpUrl.
func (s *Repository) SetHttpUrl(val OptString) {
	s.HttpUrl = val
}

// SetSshUrl sets the value of SshUrl.
func (s *Repository) SetSshUrl(val OptString) {
	s.SshUrl = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *Repository) SetDisplayOrder(val OptInt) {
	s.DisplayOrder = val
}

// SetPushedAt sets the value of PushedAt.
func (s *Repository) SetPushedAt(val OptNilString) {
	s.PushedAt = val
}

// SetCreatedUser sets the value of CreatedUser.
func (s *Repository) SetCreatedUser(val OptUser) {
	s.CreatedUser = val
}

// SetCreated sets the value of Created.
func (s *Repository) SetCreated(val OptString) {
	s.Created = val
}

// SetUpdatedUser sets the value of UpdatedUser.
func (s *Repository) SetUpdatedUser(val OptUser) {
	s.UpdatedUser = val
}

// SetUpdated sets the value of Updated.
func (s *Repository) SetUpdated(val OptString) {
	s.Updated = val
}

// Ref: #/components/schemas/Resolution
type Resolution struct {
	ID   OptInt    `json:"id"`
	Name OptString `json:"name"`
}

// GetID returns the value of ID.
func (s *Resolution) GetID() OptInt {
	return s.ID
}

// GetName returns the value of Name.
func (s *Resolution) GetName() OptString {
	return s.Name
}

// SetID sets the value of ID.
func (s *Resolution) SetID(val OptInt) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Resolution) SetName(val OptString) {
	s.Name = val
}

// Ref: #/components/schemas/SharedFile
type SharedFile struct {
	ID          OptInt    `json:"id"`
	Type        OptString `json:"type"`
	Dir         OptString `json:"dir"`
	Name        OptString `json:"name"`
	Size        OptInt    `json:"size"`
	CreatedUser OptUser   `json:"createdUser"`
	Created     OptString `json:"created"`
	UpdatedUser OptUser   `json:"updatedUser"`
	Updated     OptString `json:"updated"`
}

// GetID returns the value of ID.
func (s *SharedFile) GetID() OptInt {
	return s.ID
}

// GetType returns the value of Type.
func (s *SharedFile) GetType() OptString {
	return s.Type
}

// GetDir returns the value of Dir.
func (s *SharedFile) GetDir() OptString {
	return s.Dir
}

// GetName returns the value of Name.
func (s *SharedFile) GetName() OptString {
	return s.Name
}

// GetSize returns the value of Size.
func (s *SharedFile) GetSize() OptInt {
	return s.Size
}

// GetCreatedUser returns the value of CreatedUser.
func (s *SharedFile) GetCreatedUser() OptUser {
	return s.CreatedUser
}

// GetCreated returns the value of Created.
func (s *SharedFile) GetCreated() OptString {
	return s.Created
}

// GetUpdatedUser returns the value of UpdatedUser.
func (s *SharedFile) GetUpdatedUser() OptUser {
	return s.UpdatedUser
}

// GetUpdated returns the value of Updated.
func (s *SharedFile) GetUpdated() OptString {
	return s.Updated
}

// SetID sets the value of ID.
func (s *SharedFile) SetID(val OptInt) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *SharedFile) SetType(val OptString) {
	s.Type = val
}

// SetDir sets the value of Dir.
func (s *SharedFile) SetDir(val OptString) {
	s.Dir = val
}

// SetName sets the value of Name.
func (s *SharedFile) SetName(val OptString) {
	s.Name = val
}

// SetSize sets the value of Size.
func (s *SharedFile) SetSize(val OptInt) {
	s.Size = val
}

// SetCreatedUser sets the value of CreatedUser.
func (s *SharedFile) SetCreatedUser(val OptUser) {
	s.CreatedUser = val
}

// SetCreated sets the value of Created.
func (s *SharedFile) SetCreated(val OptString) {
	s.Created = val
}

// SetUpdatedUser sets the value of UpdatedUser.
func (s *SharedFile) SetUpdatedUser(val OptUser) {
	s.UpdatedUser = val
}

// SetUpdated sets the value of Updated.
func (s *SharedFile) SetUpdated(val OptString) {
	s.Updated = val
}

// Ref: #/components/schemas/Star
type Star struct {
	ID        OptInt       `json:"id"`
	Comment   OptNilString `json:"comment"`
	URL       OptString    `json:"url"`
	Title     OptString    `json:"title"`
	Presenter OptUser      `json:"presenter"`
	Created   OptString    `json:"created"`
}

// GetID returns the value of ID.
func (s *Star) GetID() OptInt {
	return s.ID
}

// GetComment returns the value of Comment.
func (s *Star) GetComment() OptNilString {
	return s.Comment
}

// GetURL returns the value of URL.
func (s *Star) GetURL() OptString {
	return s.URL
}

// GetTitle returns the value of Title.
func (s *Star) GetTitle() OptString {
	return s.Title
}

// GetPresenter returns the value of Presenter.
func (s *Star) GetPresenter() OptUser {
	return s.Presenter
}

// GetCreated returns the value of Created.
func (s *Star) GetCreated() OptString {
	return s.Created
}

// SetID sets the value of ID.
func (s *Star) SetID(val OptInt) {
	s.ID = val
}

// SetComment sets the value of Comment.
func (s *Star) SetComment(val OptNilString) {
	s.Comment = val
}

// SetURL sets the value of URL.
func (s *Star) SetURL(val OptString) {
	s.URL = val
}

// SetTitle sets the value of Title.
func (s *Star) SetTitle(val OptString) {
	s.Title = val
}

// SetPresenter sets the value of Presenter.
func (s *Star) SetPresenter(val OptUser) {
	s.Presenter = val
}

// SetCreated sets the value of Created.
func (s *Star) SetCreated(val OptString) {
	s.Created = val
}

// Ref: #/components/schemas/Status
type Status struct {
	ID           OptInt    `json:"id"`
	ProjectId    OptInt    `json:"projectId"`
	Name         OptString `json:"name"`
	Color        OptString `json:"color"`
	DisplayOrder OptInt    `json:"displayOrder"`
}

// GetID returns the value of ID.
func (s *Status) GetID() OptInt {
	return s.ID
}

// GetProjectId returns the value of ProjectId.
func (s *Status) GetProjectId() OptInt {
	return s.ProjectId
}

// GetName returns the value of Name.
func (s *Status) GetName() OptString {
	return s.Name
}

// GetColor returns the value of Color.
func (s *Status) GetColor() OptString {
	return s.Color
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *Status) GetDisplayOrder() OptInt {
	return s.DisplayOrder
}

// SetID sets the value of ID.
func (s *Status) SetID(val OptInt) {
	s.ID = val
}

// SetProjectId sets the value of ProjectId.
func (s *Status) SetProjectId(val OptInt) {
	s.ProjectId = val
}

// SetName sets the value of Name.
func (s *Status) SetName(val OptString) {
	s.Name = val
}

// SetColor sets the value of Color.
func (s *Status) SetColor(val OptString) {
	s.Color = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *Status) SetDisplayOrder(val OptInt) {
	s.DisplayOrder = val
}

type UpdateCommentReq struct {
	Content OptString `json:"content"`
}

// GetContent returns the value of Content.
func (s *UpdateCommentReq) GetContent() OptString {
	return s.Content
}

// SetContent sets the value of Content.
func (s *UpdateCommentReq) SetContent(val OptString) {
	s.Content = val
}

type UpdateIssueReq struct {
	Summary        OptString  `json:"summary"`
	Description    OptString  `json:"description"`
	StatusId       OptInt     `json:"statusId"`
	ResolutionId   OptInt     `json:"resolutionId"`
	PriorityId     OptInt     `json:"priorityId"`
	IssueTypeId    OptInt     `json:"issueTypeId"`
	StartDate      OptString  `json:"startDate"`
	DueDate        OptString  `json:"dueDate"`
	EstimatedHours OptFloat64 `json:"estimatedHours"`
	ActualHours    OptFloat64 `json:"actualHours"`
	AssigneeId     OptInt     `json:"assigneeId"`
	CategoryId     []int      `json:"categoryId"`
	VersionId      []int      `json:"versionId"`
	MilestoneId    []int      `json:"milestoneId"`
	Comment        OptString  `json:"comment"`
}

// GetSummary returns the value of Summary.
func (s *UpdateIssueReq) GetSummary() OptString {
	return s.Summary
}

// GetDescription returns the value of Description.
func (s *UpdateIssueReq) GetDescription() OptString {
	return s.Description
}

// GetStatusId returns the value of StatusId.
func (s *UpdateIssueReq) GetStatusId() OptInt {
	return s.StatusId
}

// GetResolutionId returns the value of ResolutionId.
func (s *UpdateIssueReq) GetResolutionId() OptInt {
	return s.ResolutionId
}

// GetPriorityId returns the value of PriorityId.
func (s *UpdateIssueReq) GetPriorityId() OptInt {
	return s.PriorityId
}

// GetIssueTypeId returns the value of IssueTypeId.
func (s *UpdateIssueReq) GetIssueTypeId() OptInt {
	return s.IssueTypeId
}

// GetStartDate returns the value of StartDate.
func (s *UpdateIssueReq) GetStartDate() OptString {
	return s.StartDate
}

// GetDueDate returns the value of DueDate.
func (s *UpdateIssueReq) GetDueDate() OptString {
	return s.DueDate
}

// GetEstimatedHours returns the value of EstimatedHours.
func (s *UpdateIssueReq) GetEstimatedHours() OptFloat64 {
	return s.EstimatedHours
}

// GetActualHours returns the value of ActualHours.
func (s *UpdateIssueReq) GetActualHours() OptFloat64 {
	return s.ActualHours
}

// GetAssigneeId returns the value of AssigneeId.
func (s *UpdateIssueReq) GetAssigneeId() OptInt {
	return s.AssigneeId
}

// GetCategoryId returns the value of CategoryId.
func (s *UpdateIssueReq) GetCategoryId() []int {
	return s.CategoryId
}

// GetVersionId returns the value of VersionId.
func (s *UpdateIssueReq) GetVersionId() []int {
	return s.VersionId
}

// GetMilestoneId returns the value of MilestoneId.
func (s *UpdateIssueReq) GetMilestoneId() []int {
	return s.MilestoneId
}

// GetComment returns the value of Comment.
func (s *UpdateIssueReq) GetComment() OptString {
	return s.Comment
}

// SetSummary sets the value of Summary.
func (s *UpdateIssueReq) SetSummary(val OptString) {
	s.Summary = val
}

// SetDescription sets the value of Description.
func (s *UpdateIssueReq) SetDescription(val OptString) {
	s.Description = val
}

// SetStatusId sets the value of StatusId.
func (s *UpdateIssueReq) SetStatusId(val OptInt) {
	s.StatusId = val
}

// SetResolutionId sets the value of ResolutionId.
func (s *UpdateIssueReq) SetResolutionId(val OptInt) {
	s.ResolutionId = val
}

// SetPriorityId sets the value of PriorityId.
func (s *UpdateIssueReq) SetPriorityId(val OptInt) {
	s.PriorityId = val
}

// SetIssueTypeId sets the value of IssueTypeId.
func (s *UpdateIssueReq) SetIssueTypeId(val OptInt) {
	s.IssueTypeId = val
}

// SetStartDate sets the value of StartDate.
func (s *UpdateIssueReq) SetStartDate(val OptString) {
	s.StartDate = val
}

// SetDueDate sets the value of DueDate.
func (s *UpdateIssueReq) SetDueDate(val OptString) {
	s.DueDate = val
}

// SetEstimatedHours sets the value of EstimatedHours.
func (s *UpdateIssueReq) SetEstimatedHours(val OptFloat64) {
	s.EstimatedHours = val
}

// SetActualHours sets the value of ActualHours.
func (s *UpdateIssueReq) SetActualHours(val OptFloat64) {
	s.ActualHours = val
}

// SetAssigneeId sets the value of AssigneeId.
func (s *UpdateIssueReq) SetAssigneeId(val OptInt) {
	s.AssigneeId = val
}

// SetCategoryId sets the value of CategoryId.
func (s *UpdateIssueReq) SetCategoryId(val []int) {
	s.CategoryId = val
}

// SetVersionId sets the value of VersionId.
func (s *UpdateIssueReq) SetVersionId(val []int) {
	s.VersionId = val
}

// SetMilestoneId sets the value of MilestoneId.
func (s *UpdateIssueReq) SetMilestoneId(val []int) {
	s.MilestoneId = val
}

// SetComment sets the value of Comment.
func (s *UpdateIssueReq) SetComment(val OptString) {
	s.Comment = val
}

type UpdateWikiReq struct {
	Name       OptString `json:"name"`
	Content    OptString `json:"content"`
	MailNotify OptString `json:"mailNotify"`
}

// GetName returns the value of Name.
func (s *UpdateWikiReq) GetName() OptString {
	return s.Name
}

// GetContent returns the value of Content.
func (s *UpdateWikiReq) GetContent() OptString {
	return s.Content
}

// GetMailNotify returns the value of MailNotify.
func (s *UpdateWikiReq) GetMailNotify() OptString {
	return s.MailNotify
}

// SetName sets the value of Name.
func (s *UpdateWikiReq) SetName(val OptString) {
	s.Name = val
}

// SetContent sets the value of Content.
func (s *UpdateWikiReq) SetContent(val OptString) {
	s.Content = val
}

// SetMailNotify sets the value of MailNotify.
func (s *UpdateWikiReq) SetMailNotify(val OptString) {
	s.MailNotify = val
}

// Ref: #/components/schemas/User
type User struct {
	ID            OptInt          `json:"id"`
	UserId        OptString       `json:"userId"`
	Name          OptString       `json:"name"`
	RoleType      OptInt          `json:"roleType"`
	Lang          OptString       `json:"lang"`
	MailAddress   OptString       `json:"mailAddress"`
	NulabAccount  OptNulabAccount `json:"nulabAccount"`
	LastLoginTime OptString       `json:"lastLoginTime"`
}

// GetID returns the value of ID.
func (s *User) GetID() OptInt {
	return s.ID
}

// GetUserId returns the value of UserId.
func (s *User) GetUserId() OptString {
	return s.UserId
}

// GetName returns the value of Name.
func (s *User) GetName() OptString {
	return s.Name
}

// GetRoleType returns the value of RoleType.
func (s *User) GetRoleType() OptInt {
	return s.RoleType
}

// GetLang returns the value of Lang.
func (s *User) GetLang() OptString {
	return s.Lang
}

// GetMailAddress returns the value of MailAddress.
func (s *User) GetMailAddress() OptString {
	return s.MailAddress
}

// GetNulabAccount returns the value of NulabAccount.
func (s *User) GetNulabAccount() OptNulabAccount {
	return s.NulabAccount
}

// GetLastLoginTime returns the value of LastLoginTime.
func (s *User) GetLastLoginTime() OptString {
	return s.LastLoginTime
}

// SetID sets the value of ID.
func (s *User) SetID(val OptInt) {
	s.ID = val
}

// SetUserId sets the value of UserId.
func (s *User) SetUserId(val OptString) {
	s.UserId = val
}

// SetName sets the value of Name.
func (s *User) SetName(val OptString) {
	s.Name = val
}

// SetRoleType sets the value of RoleType.
func (s *User) SetRoleType(val OptInt) {
	s.RoleType = val
}

// SetLang sets the value of Lang.
func (s *User) SetLang(val OptString) {
	s.Lang = val
}

// SetMailAddress sets the value of MailAddress.
func (s *User) SetMailAddress(val OptString) {
	s.MailAddress = val
}

// SetNulabAccount sets the value of NulabAccount.
func (s *User) SetNulabAccount(val OptNulabAccount) {
	s.NulabAccount = val
}

// SetLastLoginTime sets the value of LastLoginTime.
func (s *User) SetLastLoginTime(val OptString) {
	s.LastLoginTime = val
}

// Ref: #/components/schemas/Version
type Version struct {
	ID             OptInt       `json:"id"`
	ProjectId      OptInt       `json:"projectId"`
	Name           OptString    `json:"name"`
	Description    OptNilString `json:"description"`
	StartDate      OptNilString `json:"startDate"`
	ReleaseDueDate OptNilString `json:"releaseDueDate"`
	Archived       OptBool      `json:"archived"`
	DisplayOrder   OptInt       `json:"displayOrder"`
}

// GetID returns the value of ID.
func (s *Version) GetID() OptInt {
	return s.ID
}

// GetProjectId returns the value of ProjectId.
func (s *Version) GetProjectId() OptInt {
	return s.ProjectId
}

// GetName returns the value of Name.
func (s *Version) GetName() OptString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Version) GetDescription() OptNilString {
	return s.Description
}

// GetStartDate returns the value of StartDate.
func (s *Version) GetStartDate() OptNilString {
	return s.StartDate
}

// GetReleaseDueDate returns the value of ReleaseDueDate.
func (s *Version) GetReleaseDueDate() OptNilString {
	return s.ReleaseDueDate
}

// GetArchived returns the value of Archived.
func (s *Version) GetArchived() OptBool {
	return s.Archived
}

// GetDisplayOrder returns the value of DisplayOrder.
func (s *Version) GetDisplayOrder() OptInt {
	return s.DisplayOrder
}

// SetID sets the value of ID.
func (s *Version) SetID(val OptInt) {
	s.ID = val
}

// SetProjectId sets the value of ProjectId.
func (s *Version) SetProjectId(val OptInt) {
	s.ProjectId = val
}

// SetName sets the value of Name.
func (s *Version) SetName(val OptString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Version) SetDescription(val OptNilString) {
	s.Description = val
}

// SetStartDate sets the value of StartDate.
func (s *Version) SetStartDate(val OptNilString) {
	s.StartDate = val
}

// SetReleaseDueDate sets the value of ReleaseDueDate.
func (s *Version) SetReleaseDueDate(val OptNilString) {
	s.ReleaseDueDate = val
}

// SetArchived sets the value of Archived.
func (s *Version) SetArchived(val OptBool) {
	s.Archived = val
}

// SetDisplayOrder sets the value of DisplayOrder.
func (s *Version) SetDisplayOrder(val OptInt) {
	s.DisplayOrder = val
}

// Ref: #/components/schemas/Wiki
type Wiki struct {
	ID          OptInt       `json:"id"`
	ProjectId   OptInt       `json:"projectId"`
	Name        OptString    `json:"name"`
	Content     OptString    `json:"content"`
	Tags        []WikiTag    `json:"tags"`
	Attachments []Attachment `json:"attachments"`
	SharedFiles []SharedFile `json:"sharedFiles"`
	Stars       []Star       `json:"stars"`
	CreatedUser OptUser      `json:"createdUser"`
	Created     OptString    `json:"created"`
	UpdatedUser OptUser      `json:"updatedUser"`
	Updated     OptNilString `json:"updated"`
}

// GetID returns the value of ID.
func (s *Wiki) GetID() OptInt {
	return s.ID
}

// GetProjectId returns the value of ProjectId.
func (s *Wiki) GetProjectId() OptInt {
	return s.ProjectId
}

// GetName returns the value of Name.
func (s *Wiki) GetName() OptString {
	return s.Name
}

// GetContent returns the value of Content.
func (s *Wiki) GetContent() OptString {
	return s.Content
}

// GetTags returns the value of Tags.
func (s *Wiki) GetTags() []WikiTag {
	return s.Tags
}

// GetAttachments returns the value of Attachments.
func (s *Wiki) GetAttachments() []Attachment {
	return s.Attachments
}

// GetSharedFiles returns the value of SharedFiles.
func (s *Wiki) GetSharedFiles() []SharedFile {
	return s.SharedFiles
}

// GetStars returns the value of Stars.
func (s *Wiki) GetStars() []Star {
	return s.Stars
}

// GetCreatedUser returns the value of CreatedUser.
func (s *Wiki) GetCreatedUser() OptUser {
	return s.CreatedUser
}

// GetCreated returns the value of Created.
func (s *Wiki) GetCreated() OptString {
	return s.Created
}

// GetUpdatedUser returns the value of UpdatedUser.
func (s *Wiki) GetUpdatedUser() OptUser {
	return s.UpdatedUser
}

// GetUpdated returns the value of Updated.
func (s *Wiki) GetUpdated() OptNilString {
	return s.Updated
}

// SetID sets the value of ID.
func (s *Wiki) SetID(val OptInt) {
	s.ID = val
}

// SetProjectId sets the value of ProjectId.
func (s *Wiki) SetProjectId(val OptInt) {
	s.ProjectId = val
}

// SetName sets the value of Name.
func (s *Wiki) SetName(val OptString) {
	s.Name = val
}

// SetContent sets the value of Content.
func (s *Wiki) SetContent(val OptString) {
	s.Content = val
}

// SetTags sets the value of Tags.
func (s *Wiki) SetTags(val []WikiTag) {
	s.Tags = val
}

// SetAttachments sets the value of Attachments.
func (s *Wiki) SetAttachments(val []Attachment) {
	s.Attachments = val
}

// SetSharedFiles sets the value of SharedFiles.
func (s *Wiki) SetSharedFiles(val []SharedFile) {
	s.SharedFiles = val
}

// SetStars sets the value of Stars.
func (s *Wiki) SetStars(val []Star) {
	s.Stars = val
}

// SetCreatedUser sets the value of CreatedUser.
func (s *Wiki) SetCreatedUser(val OptUser) {
	s.CreatedUser = val
}

// SetCreated sets the value of Created.
func (s *Wiki) SetCreated(val OptString) {
	s.Created = val
}

// SetUpdatedUser sets the value of UpdatedUser.
func (s *Wiki) SetUpdatedUser(val OptUser) {
	s.UpdatedUser = val
}

// SetUpdated sets the value of Updated.
func (s *Wiki) SetUpdated(val OptNilString) {
	s.Updated = val
}

// Ref: #/components/schemas/WikiTag
type WikiTag struct {
	ID   OptInt    `json:"id"`
	Name OptString `json:"name"`
}

// GetID returns the value of ID.
func (s *WikiTag) GetID() OptInt {
	return s.ID
}

// GetName returns the value of Name.
func (s *WikiTag) GetName() OptString {
	return s.Name
}

// SetID sets the value of ID.
func (s *WikiTag) SetID(val OptInt) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *WikiTag) SetName(val OptString) {
	s.Name = val
}
