// Code generated by ogen, DO NOT EDIT.

package backlog

// OperationName is the ogen operation name
type OperationName = string

const (
	AddCommentOperation           OperationName = "AddComment"
	CreateIssueOperation          OperationName = "CreateIssue"
	CreateWikiOperation           OperationName = "CreateWiki"
	DeleteIssueOperation          OperationName = "DeleteIssue"
	DeleteWikiOperation           OperationName = "DeleteWiki"
	GetCategoriesOperation        OperationName = "GetCategories"
	GetCommentOperation           OperationName = "GetComment"
	GetCommentsOperation          OperationName = "GetComments"
	GetCommentsCountOperation     OperationName = "GetCommentsCount"
	GetCurrentUserOperation       OperationName = "GetCurrentUser"
	GetIssueOperation             OperationName = "GetIssue"
	GetIssueTypesOperation        OperationName = "GetIssueTypes"
	GetIssuesOperation            OperationName = "GetIssues"
	GetIssuesCountOperation       OperationName = "GetIssuesCount"
	GetProjectOperation           OperationName = "GetProject"
	GetProjectUsersOperation      OperationName = "GetProjectUsers"
	GetProjectsOperation          OperationName = "GetProjects"
	GetPullRequestOperation       OperationName = "GetPullRequest"
	GetPullRequestsOperation      OperationName = "GetPullRequests"
	GetPullRequestsCountOperation OperationName = "GetPullRequestsCount"
	GetRepositoriesOperation      OperationName = "GetRepositories"
	GetStatusesOperation          OperationName = "GetStatuses"
	GetUserOperation              OperationName = "GetUser"
	GetVersionsOperation          OperationName = "GetVersions"
	GetWikiOperation              OperationName = "GetWiki"
	GetWikisOperation             OperationName = "GetWikis"
	GetWikisCountOperation        OperationName = "GetWikisCount"
	UpdateCommentOperation        OperationName = "UpdateComment"
	UpdateIssueOperation          OperationName = "UpdateIssue"
	UpdateWikiOperation           OperationName = "UpdateWiki"
)
