#!/usr/bin/env npx tsx
/**
 * Development setup script for Cloudflare Workers
 *
 * このスクリプトは config.ts から .dev.vars ファイルを生成します。
 * .dev.vars は wrangler dev で使用されるローカル開発用の環境変数ファイルです。
 *
 * 使用方法:
 *   pnpm dev:setup   # .dev.vars を生成
 *   pnpm dev         # ローカル開発サーバーを起動（自動で dev:setup を実行）
 */

import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(__dirname, "..");

async function loadConfig(): Promise<{ config: unknown }> {
  const configPath = resolve(packageRoot, "config.ts");

  if (!existsSync(configPath)) {
    console.error("Error: config.ts not found");
    console.error("");
    console.error("Please create config.ts from the example:");
    console.error("  cp config.example.ts config.ts");
    console.error("");
    console.error("Then edit config.ts with your settings.");
    process.exit(1);
  }

  // Dynamic import with file:// URL for Windows compatibility
  const configModule = await import(`file://${configPath}`);
  return { config: configModule.config };
}

function generateDevVars(config: unknown): string {
  const lines: string[] = [
    "# Auto-generated from config.ts",
    "# Do not edit this file directly - modify config.ts instead",
    "#",
    `# Generated at: ${new Date().toISOString()}`,
    "",
  ];

  // RELAY_CONFIG as JSON string
  const configJson = JSON.stringify(config);
  lines.push(`RELAY_CONFIG=${configJson}`);

  return lines.join("\n") + "\n";
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);

  if (args.includes("--help") || args.includes("-h")) {
    console.log("Usage: dev-setup.ts [options]");
    console.log("");
    console.log("Generate .dev.vars from config.ts for local development.");
    console.log("");
    console.log("Options:");
    console.log("  --help, -h    Show this help");
    process.exit(0);
  }

  console.log("Loading config.ts...");
  const { config } = await loadConfig();

  console.log("Generating .dev.vars...");
  const devVarsContent = generateDevVars(config);
  const devVarsPath = resolve(packageRoot, ".dev.vars");

  writeFileSync(devVarsPath, devVarsContent, "utf-8");
  console.log(`Created: ${devVarsPath}`);

  console.log("");
  console.log("You can now run: pnpm dev");
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
