// Code generated by jubako generate paths. DO NOT EDIT.
// Source: resolved.go
// Type: ResolvedConfig
//go:generate go tool jubako generate paths -type ResolvedConfig resolved.go

package config

import (
	"strconv"

	"github.com/yacchi/jubako/jsonptr"
)

// Path constants for static configuration paths.
const (
	PathActiveProfile                      = "/active_profile"
	PathProfile                            = "/profile"
	PathCredential                         = "/credential"
	PathClientTrustBundles                 = "/client/trust/bundles"
	PathProjectProfile                     = "/project/profile"
	PathProjectSpace                       = "/project/space"
	PathProjectDomain                      = "/project/domain"
	PathProjectName                        = "/project/name"
	PathServerHost                         = "/server/host"
	PathServerPort                         = "/server/port"
	PathServerBaseUrl                      = "/server/base_url"
	PathServerAllowedHostPatterns          = "/server/allowed_host_patterns"
	PathServerHttpReadTimeout              = "/server/http/read_timeout"
	PathServerHttpWriteTimeout             = "/server/http/write_timeout"
	PathServerHttpIdleTimeout              = "/server/http/idle_timeout"
	PathServerJwtExpiry                    = "/server/jwt/expiry"
	PathServerCacheShortTtl                = "/server/cache/short_ttl"
	PathServerCacheLongTtl                 = "/server/cache/long_ttl"
	PathServerCacheStaticTtl               = "/server/cache/static_ttl"
	PathServerBacklog                      = "/server/backlog"
	PathServerTenants                      = "/server/tenants"
	PathServerAccessControlAllowedSpaces   = "/server/access_control/allowed_spaces"
	PathServerAccessControlAllowedProjects = "/server/access_control/allowed_projects"
	PathServerAccessControlAllowedCidrs    = "/server/access_control/allowed_cidrs"
	PathServerRateLimitEnabled             = "/server/rate_limit/enabled"
	PathServerRateLimitRequestsPerMinute   = "/server/rate_limit/requests_per_minute"
	PathServerRateLimitBurst               = "/server/rate_limit/burst"
	PathServerRateLimitCleanupInterval     = "/server/rate_limit/cleanup_interval"
	PathServerRateLimitEntryTtl            = "/server/rate_limit/entry_ttl"
	PathServerAuditEnabled                 = "/server/audit/enabled"
	PathServerAuditOutput                  = "/server/audit/output"
	PathServerAuditFilePath                = "/server/audit/file_path"
	PathServerAuditWebhookUrl              = "/server/audit/webhook_url"
	PathServerAuditWebhookTimeout          = "/server/audit/webhook_timeout"
	PathDisplaySummaryMaxLength            = "/display/summary_max_length"
	PathDisplaySummaryCommentCount         = "/display/summary_comment_count"
	PathDisplayDefaultCommentCount         = "/display/default_comment_count"
	PathDisplayDefaultIssueLimit           = "/display/default_issue_limit"
	PathDisplayTimezone                    = "/display/timezone"
	PathDisplayDateFormat                  = "/display/date_format"
	PathDisplayDatetimeFormat              = "/display/datetime_format"
	PathDisplayHyperlink                   = "/display/hyperlink"
	PathDisplayMarkdownView                = "/display/markdown_view"
	PathDisplayMarkdownWarn                = "/display/markdown_warn"
	PathDisplayMarkdownCache               = "/display/markdown_cache"
	PathDisplayMarkdownCacheRaw            = "/display/markdown_cache_raw"
	PathDisplayMarkdownCacheExcerpt        = "/display/markdown_cache_excerpt"
	PathDisplayMarkdownUnsafeRules         = "/display/markdown_unsafe_rules"
	PathDisplayIssueListFields             = "/display/issue_list_fields"
	PathDisplayIssueFieldConfig            = "/display/issue_field_config"
	PathDisplayPrListFields                = "/display/pr_list_fields"
	PathDisplayPrFieldConfig               = "/display/pr_field_config"
	PathAuthMinCallbackPort                = "/auth/min_callback_port"
	PathAuthMaxCallbackPort                = "/auth/max_callback_port"
	PathAuthSessionCheckInterval           = "/auth/session/check_interval"
	PathAuthSessionTimeout                 = "/auth/session/timeout"
	PathAuthKeepaliveInterval              = "/auth/keepalive/interval"
	PathAuthKeepaliveTimeout               = "/auth/keepalive/timeout"
	PathAuthKeepaliveConnectTimeout        = "/auth/keepalive/connect_timeout"
	PathAuthKeepaliveGracePeriod           = "/auth/keepalive/grace_period"
	PathCacheEnabled                       = "/cache/enabled"
	PathCacheDir                           = "/cache/dir"
	PathCacheTtl                           = "/cache/ttl"
)

// PathProfileRelayServer returns the JSONPointer path.
// Path pattern: /profile/{key}/relay_server
func PathProfileRelayServer(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/relay_server"
}

// PathProfileSpace returns the JSONPointer path.
// Path pattern: /profile/{key}/space
func PathProfileSpace(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/space"
}

// PathProfileDomain returns the JSONPointer path.
// Path pattern: /profile/{key}/domain
func PathProfileDomain(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/domain"
}

// PathProfileProject returns the JSONPointer path.
// Path pattern: /profile/{key}/project
func PathProfileProject(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/project"
}

// PathProfileOutput returns the JSONPointer path.
// Path pattern: /profile/{key}/output
func PathProfileOutput(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/output"
}

// PathProfileJsonFields returns the JSONPointer path.
// Path pattern: /profile/{key}/json_fields
func PathProfileJsonFields(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/json_fields"
}

// PathProfileJq returns the JSONPointer path.
// Path pattern: /profile/{key}/jq
func PathProfileJq(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/jq"
}

// PathProfileColor returns the JSONPointer path.
// Path pattern: /profile/{key}/color
func PathProfileColor(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/color"
}

// PathProfileEditor returns the JSONPointer path.
// Path pattern: /profile/{key}/editor
func PathProfileEditor(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/editor"
}

// PathProfileBrowser returns the JSONPointer path.
// Path pattern: /profile/{key}/browser
func PathProfileBrowser(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/browser"
}

// PathProfileAuthCallbackPort returns the JSONPointer path.
// Path pattern: /profile/{key}/auth_callback_port
func PathProfileAuthCallbackPort(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/auth_callback_port"
}

// PathProfileAuthTimeout returns the JSONPointer path.
// Path pattern: /profile/{key}/auth_timeout
func PathProfileAuthTimeout(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/auth_timeout"
}

// PathProfileAuthNoBrowser returns the JSONPointer path.
// Path pattern: /profile/{key}/auth_no_browser
func PathProfileAuthNoBrowser(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/auth_no_browser"
}

// PathProfileAuthSkipConfirmation returns the JSONPointer path.
// Path pattern: /profile/{key}/auth_skip_confirmation
func PathProfileAuthSkipConfirmation(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/auth_skip_confirmation"
}

// PathProfileHttpTimeout returns the JSONPointer path.
// Path pattern: /profile/{key}/http_timeout
func PathProfileHttpTimeout(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/http_timeout"
}

// PathProfileHttpTokenRefreshMargin returns the JSONPointer path.
// Path pattern: /profile/{key}/http_token_refresh_margin
func PathProfileHttpTokenRefreshMargin(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/http_token_refresh_margin"
}

// PathCredentialAuthType returns the JSONPointer path.
// Path pattern: /credential/{key}/auth_type
func PathCredentialAuthType(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/auth_type"
}

// PathCredentialAccessToken returns the JSONPointer path.
// Path pattern: /credential/{key}/access_token
func PathCredentialAccessToken(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/access_token"
}

// PathCredentialRefreshToken returns the JSONPointer path.
// Path pattern: /credential/{key}/refresh_token
func PathCredentialRefreshToken(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/refresh_token"
}

// PathCredentialExpiresAt returns the JSONPointer path.
// Path pattern: /credential/{key}/expires_at
func PathCredentialExpiresAt(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/expires_at"
}

// PathCredentialApiKey returns the JSONPointer path.
// Path pattern: /credential/{key}/api_key
func PathCredentialApiKey(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/api_key"
}

// PathCredentialUserId returns the JSONPointer path.
// Path pattern: /credential/{key}/user_id
func PathCredentialUserId(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/user_id"
}

// PathCredentialUserName returns the JSONPointer path.
// Path pattern: /credential/{key}/user_name
func PathCredentialUserName(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/user_name"
}

// PathClientTrustBundlesId returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/id
func PathClientTrustBundlesId(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/id"
}

// PathClientTrustBundlesRelayUrl returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/relay_url
func PathClientTrustBundlesRelayUrl(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/relay_url"
}

// PathClientTrustBundlesAllowedDomain returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/allowed_domain
func PathClientTrustBundlesAllowedDomain(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/allowed_domain"
}

// PathClientTrustBundlesBundleToken returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/bundle_token
func PathClientTrustBundlesBundleToken(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/bundle_token"
}

// PathClientTrustBundlesRelayKeys returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/relay_keys
func PathClientTrustBundlesRelayKeys(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/relay_keys"
}

// PathClientTrustBundlesRelayKeysKeyId returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/relay_keys/{index2}/key_id
func PathClientTrustBundlesRelayKeysKeyId(index int, index2 int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/relay_keys/" + strconv.Itoa(index2) + "/key_id"
}

// PathClientTrustBundlesRelayKeysThumbprint returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/relay_keys/{index2}/thumbprint
func PathClientTrustBundlesRelayKeysThumbprint(index int, index2 int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/relay_keys/" + strconv.Itoa(index2) + "/thumbprint"
}

// PathClientTrustBundlesIssuedAt returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/issued_at
func PathClientTrustBundlesIssuedAt(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/issued_at"
}

// PathClientTrustBundlesExpiresAt returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/expires_at
func PathClientTrustBundlesExpiresAt(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/expires_at"
}

// PathClientTrustBundlesCertsCacheTtl returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/certs_cache_ttl
func PathClientTrustBundlesCertsCacheTtl(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/certs_cache_ttl"
}

// PathClientTrustBundlesSourceFileName returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/source/file_name
func PathClientTrustBundlesSourceFileName(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/source/file_name"
}

// PathClientTrustBundlesSourceSha256 returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/source/sha256
func PathClientTrustBundlesSourceSha256(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/source/sha256"
}

// PathClientTrustBundlesImportedAt returns the JSONPointer path.
// Path pattern: /client/trust/bundles/{index}/imported_at
func PathClientTrustBundlesImportedAt(index int) string {
	return "/client/trust/bundles/" + strconv.Itoa(index) + "/imported_at"
}

// PathServerBacklogDomain returns the JSONPointer path.
// Path pattern: /server/backlog/{key}/domain
func PathServerBacklogDomain(key string) string {
	return "/server/backlog/" + jsonptr.Escape(key) + "/domain"
}

// PathServerBacklogClientId returns the JSONPointer path.
// Path pattern: /server/backlog/{key}/client_id
func PathServerBacklogClientId(key string) string {
	return "/server/backlog/" + jsonptr.Escape(key) + "/client_id"
}

// PathServerBacklogClientSecret returns the JSONPointer path.
// Path pattern: /server/backlog/{key}/client_secret
func PathServerBacklogClientSecret(key string) string {
	return "/server/backlog/" + jsonptr.Escape(key) + "/client_secret"
}

// PathServerTenantsJwks returns the JSONPointer path.
// Path pattern: /server/tenants/{key}/jwks
func PathServerTenantsJwks(key string) string {
	return "/server/tenants/" + jsonptr.Escape(key) + "/jwks"
}

// PathServerTenantsActiveKeys returns the JSONPointer path.
// Path pattern: /server/tenants/{key}/active_keys
func PathServerTenantsActiveKeys(key string) string {
	return "/server/tenants/" + jsonptr.Escape(key) + "/active_keys"
}

// PathServerTenantsAllowedDomain returns the JSONPointer path.
// Path pattern: /server/tenants/{key}/allowed_domain
func PathServerTenantsAllowedDomain(key string) string {
	return "/server/tenants/" + jsonptr.Escape(key) + "/allowed_domain"
}

// PathServerTenantsInfoTtl returns the JSONPointer path.
// Path pattern: /server/tenants/{key}/info_ttl
func PathServerTenantsInfoTtl(key string) string {
	return "/server/tenants/" + jsonptr.Escape(key) + "/info_ttl"
}

// PathServerTenantsPassphraseHash returns the JSONPointer path.
// Path pattern: /server/tenants/{key}/passphrase_hash
func PathServerTenantsPassphraseHash(key string) string {
	return "/server/tenants/" + jsonptr.Escape(key) + "/passphrase_hash"
}

// PathDisplayIssueFieldConfigHeader returns the JSONPointer path.
// Path pattern: /display/issue_field_config/{key}/header
func PathDisplayIssueFieldConfigHeader(key string) string {
	return "/display/issue_field_config/" + jsonptr.Escape(key) + "/header"
}

// PathDisplayIssueFieldConfigMaxWidth returns the JSONPointer path.
// Path pattern: /display/issue_field_config/{key}/max_width
func PathDisplayIssueFieldConfigMaxWidth(key string) string {
	return "/display/issue_field_config/" + jsonptr.Escape(key) + "/max_width"
}

// PathDisplayIssueFieldConfigTimeFormat returns the JSONPointer path.
// Path pattern: /display/issue_field_config/{key}/time_format
func PathDisplayIssueFieldConfigTimeFormat(key string) string {
	return "/display/issue_field_config/" + jsonptr.Escape(key) + "/time_format"
}

// PathDisplayPrFieldConfigHeader returns the JSONPointer path.
// Path pattern: /display/pr_field_config/{key}/header
func PathDisplayPrFieldConfigHeader(key string) string {
	return "/display/pr_field_config/" + jsonptr.Escape(key) + "/header"
}

// PathDisplayPrFieldConfigMaxWidth returns the JSONPointer path.
// Path pattern: /display/pr_field_config/{key}/max_width
func PathDisplayPrFieldConfigMaxWidth(key string) string {
	return "/display/pr_field_config/" + jsonptr.Escape(key) + "/max_width"
}

// PathDisplayPrFieldConfigTimeFormat returns the JSONPointer path.
// Path pattern: /display/pr_field_config/{key}/time_format
func PathDisplayPrFieldConfigTimeFormat(key string) string {
	return "/display/pr_field_config/" + jsonptr.Escape(key) + "/time_format"
}
