// Code generated by jubako generate paths. DO NOT EDIT.
// Source: resolved.go
// Type: ResolvedConfig
//go:generate go tool jubako generate paths -type ResolvedConfig resolved.go

package config

import (
	"github.com/yacchi/jubako/jsonptr"
)

// Path constants for static configuration paths.
const (
	PathActiveProfile                      = "/active_profile"
	PathProfile                            = "/profile"
	PathCredential                         = "/credential"
	PathProjectProfile                     = "/project/profile"
	PathProjectSpace                       = "/project/space"
	PathProjectDomain                      = "/project/domain"
	PathProjectName                        = "/project/name"
	PathServerHost                         = "/server/host"
	PathServerPort                         = "/server/port"
	PathServerBaseUrl                      = "/server/base_url"
	PathServerHttpReadTimeout              = "/server/http/read_timeout"
	PathServerHttpWriteTimeout             = "/server/http/write_timeout"
	PathServerHttpIdleTimeout              = "/server/http/idle_timeout"
	PathServerJwtExpiry                    = "/server/jwt/expiry"
	PathServerBacklog                      = "/server/backlog"
	PathServerAccessControlAllowedSpaces   = "/server/access_control/allowed_spaces"
	PathServerAccessControlAllowedProjects = "/server/access_control/allowed_projects"
	PathServerAccessControlAllowedCidrs    = "/server/access_control/allowed_cidrs"
	PathServerRateLimitEnabled             = "/server/rate_limit/enabled"
	PathServerRateLimitRequestsPerMinute   = "/server/rate_limit/requests_per_minute"
	PathServerRateLimitBurst               = "/server/rate_limit/burst"
	PathServerRateLimitCleanupInterval     = "/server/rate_limit/cleanup_interval"
	PathServerRateLimitEntryTtl            = "/server/rate_limit/entry_ttl"
	PathServerAuditEnabled                 = "/server/audit/enabled"
	PathServerAuditOutput                  = "/server/audit/output"
	PathServerAuditFilePath                = "/server/audit/file_path"
	PathServerAuditWebhookUrl              = "/server/audit/webhook_url"
	PathServerAuditWebhookTimeout          = "/server/audit/webhook_timeout"
	PathDisplaySummaryMaxLength            = "/display/summary_max_length"
	PathDisplayDefaultCommentCount         = "/display/default_comment_count"
	PathDisplayDefaultIssueLimit           = "/display/default_issue_limit"
	PathDisplayTimezone                    = "/display/timezone"
	PathDisplayDateFormat                  = "/display/date_format"
	PathDisplayDatetimeFormat              = "/display/datetime_format"
	PathDisplayHyperlink                   = "/display/hyperlink"
	PathDisplayIssueListFields             = "/display/issue_list_fields"
	PathDisplayIssueFieldConfig            = "/display/issue_field_config"
	PathDisplayPrListFields                = "/display/pr_list_fields"
	PathDisplayPrFieldConfig               = "/display/pr_field_config"
	PathAuthMinCallbackPort                = "/auth/min_callback_port"
	PathAuthMaxCallbackPort                = "/auth/max_callback_port"
)

// PathProfileRelayServer returns the JSONPointer path.
// Path pattern: /profile/{key}/relay_server
func PathProfileRelayServer(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/relay_server"
}

// PathProfileSpace returns the JSONPointer path.
// Path pattern: /profile/{key}/space
func PathProfileSpace(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/space"
}

// PathProfileDomain returns the JSONPointer path.
// Path pattern: /profile/{key}/domain
func PathProfileDomain(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/domain"
}

// PathProfileProject returns the JSONPointer path.
// Path pattern: /profile/{key}/project
func PathProfileProject(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/project"
}

// PathProfileOutput returns the JSONPointer path.
// Path pattern: /profile/{key}/output
func PathProfileOutput(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/output"
}

// PathProfileFormat returns the JSONPointer path.
// Path pattern: /profile/{key}/format
func PathProfileFormat(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/format"
}

// PathProfileColor returns the JSONPointer path.
// Path pattern: /profile/{key}/color
func PathProfileColor(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/color"
}

// PathProfileEditor returns the JSONPointer path.
// Path pattern: /profile/{key}/editor
func PathProfileEditor(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/editor"
}

// PathProfileBrowser returns the JSONPointer path.
// Path pattern: /profile/{key}/browser
func PathProfileBrowser(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/browser"
}

// PathProfileAuthCallbackPort returns the JSONPointer path.
// Path pattern: /profile/{key}/auth_callback_port
func PathProfileAuthCallbackPort(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/auth_callback_port"
}

// PathProfileAuthTimeout returns the JSONPointer path.
// Path pattern: /profile/{key}/auth_timeout
func PathProfileAuthTimeout(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/auth_timeout"
}

// PathProfileAuthNoBrowser returns the JSONPointer path.
// Path pattern: /profile/{key}/auth_no_browser
func PathProfileAuthNoBrowser(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/auth_no_browser"
}

// PathProfileHttpTimeout returns the JSONPointer path.
// Path pattern: /profile/{key}/http_timeout
func PathProfileHttpTimeout(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/http_timeout"
}

// PathProfileHttpTokenRefreshMargin returns the JSONPointer path.
// Path pattern: /profile/{key}/http_token_refresh_margin
func PathProfileHttpTokenRefreshMargin(key string) string {
	return "/profile/" + jsonptr.Escape(key) + "/http_token_refresh_margin"
}

// PathCredentialAuthType returns the JSONPointer path.
// Path pattern: /credential/{key}/auth_type
func PathCredentialAuthType(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/auth_type"
}

// PathCredentialAccessToken returns the JSONPointer path.
// Path pattern: /credential/{key}/access_token
func PathCredentialAccessToken(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/access_token"
}

// PathCredentialRefreshToken returns the JSONPointer path.
// Path pattern: /credential/{key}/refresh_token
func PathCredentialRefreshToken(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/refresh_token"
}

// PathCredentialExpiresAt returns the JSONPointer path.
// Path pattern: /credential/{key}/expires_at
func PathCredentialExpiresAt(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/expires_at"
}

// PathCredentialApiKey returns the JSONPointer path.
// Path pattern: /credential/{key}/api_key
func PathCredentialApiKey(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/api_key"
}

// PathCredentialUserId returns the JSONPointer path.
// Path pattern: /credential/{key}/user_id
func PathCredentialUserId(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/user_id"
}

// PathCredentialUserName returns the JSONPointer path.
// Path pattern: /credential/{key}/user_name
func PathCredentialUserName(key string) string {
	return "/credential/" + jsonptr.Escape(key) + "/user_name"
}

// PathServerBacklogDomain returns the JSONPointer path.
// Path pattern: /server/backlog/{key}/domain
func PathServerBacklogDomain(key string) string {
	return "/server/backlog/" + jsonptr.Escape(key) + "/domain"
}

// PathServerBacklogClientId returns the JSONPointer path.
// Path pattern: /server/backlog/{key}/client_id
func PathServerBacklogClientId(key string) string {
	return "/server/backlog/" + jsonptr.Escape(key) + "/client_id"
}

// PathServerBacklogClientSecret returns the JSONPointer path.
// Path pattern: /server/backlog/{key}/client_secret
func PathServerBacklogClientSecret(key string) string {
	return "/server/backlog/" + jsonptr.Escape(key) + "/client_secret"
}

// PathDisplayIssueFieldConfigHeader returns the JSONPointer path.
// Path pattern: /display/issue_field_config/{key}/header
func PathDisplayIssueFieldConfigHeader(key string) string {
	return "/display/issue_field_config/" + jsonptr.Escape(key) + "/header"
}

// PathDisplayIssueFieldConfigMaxWidth returns the JSONPointer path.
// Path pattern: /display/issue_field_config/{key}/max_width
func PathDisplayIssueFieldConfigMaxWidth(key string) string {
	return "/display/issue_field_config/" + jsonptr.Escape(key) + "/max_width"
}

// PathDisplayIssueFieldConfigTimeFormat returns the JSONPointer path.
// Path pattern: /display/issue_field_config/{key}/time_format
func PathDisplayIssueFieldConfigTimeFormat(key string) string {
	return "/display/issue_field_config/" + jsonptr.Escape(key) + "/time_format"
}

// PathDisplayPrFieldConfigHeader returns the JSONPointer path.
// Path pattern: /display/pr_field_config/{key}/header
func PathDisplayPrFieldConfigHeader(key string) string {
	return "/display/pr_field_config/" + jsonptr.Escape(key) + "/header"
}

// PathDisplayPrFieldConfigMaxWidth returns the JSONPointer path.
// Path pattern: /display/pr_field_config/{key}/max_width
func PathDisplayPrFieldConfigMaxWidth(key string) string {
	return "/display/pr_field_config/" + jsonptr.Escape(key) + "/max_width"
}

// PathDisplayPrFieldConfigTimeFormat returns the JSONPointer path.
// Path pattern: /display/pr_field_config/{key}/time_format
func PathDisplayPrFieldConfigTimeFormat(key string) string {
	return "/display/pr_field_config/" + jsonptr.Escape(key) + "/time_format"
}
